### ISSUE TITLE
Cannot be installed using package manager

### ISSUE THREAD

**Issue by luto65** [hackiftekhar/IQListKit#2]
https://github.com/hackiftekhar/IQListKit.git has no Package.swift manifest for version ... https://github.com/hackiftekhar/IQListKit.git

the manifest is missing a Swift tools version specification; consider prepending to the manifest 
'// swift-tools-version:5.4.0' 
to specify the current Swift toolchain version as the lowest Swift version supported by the project; 
if such a specification already exists, consider moving it to the top of the manifest, or prepending it with 
'//' 
to help Swift Package Manager find it

**Comment by hackiftekhar** [comment]
- Added support for package manager
